language: nodes_js
cache:
  directories:
    - ~/.npm
nodes_js:
  - node
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target-branch: gh-pages
  commit_message: "Deploy Realease"
  on:
    branch: main
